plugins {
    id 'groovy'
    id 'application'
}

application {
    mainClass = 'Main'
}

tasks.register('runApi', JavaExec) {
    group = 'application'
    description = 'Inicia API REST'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'groovy.api.ApiMain'
}

run {
    standardInput = System.in
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:5.0.0'
    implementation 'org.apache.groovy:groovy-json:5.0.0'
    implementation 'org.postgresql:postgresql:42.7.2'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

sourceSets {
    main {
        groovy {
            srcDirs = ['src/groovy']
            exclude 'test/**'
        }
    }
    test {
        groovy {
            srcDirs = ['src/groovy/test']
        }
    }
}
